# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYpM5T8BylZVjolqkfupMs6TZhXXUrpD
"""



"""# DIA
## Temario:
- Tipos de datos
- Operaciones matemáticas
- Operaciones con string
- Operaciones Logicas
- Operaciones Booleanas

## Tipos de Datos
"""

# Existen los datos:
enteros = 4 # Son numeros sin decimales
flotantes = 3.9 # Son numeros con decimales
type(enteros)

# Caracteres/ Strings
caracteres = "a"
cadena_caracteres = "Hola mundo"
type(cadena_caracteres)

# Booleanos
falso = False # falso es 0
verdadero = True # verdadero es 1

# imprimir
print(enteros)

"""### Espera, el usuario tambien puede ingresar datos"""

# Con la funcion input, el usuario puede ingresar cualquier tipo de dato
# y podemos guardarlo en alguna variable
name = input("Mi nombre es: ") # te lo guarda como un string
print(name)

num = input("Ingresa un numero: ")
print(num + 1)

num = int(input("Ingresa un numero: "))
print(num + 1)

"""## Operaciones matematicas"""

# 4to Nivel de Importancia
# Suma Ordinaria
print("Suma ordinaria: ")
print(3 + 4)
variable1,variable2 = 20,40 # 60
print(variable1 + variable2)

# Resta Ordinaria
print("Resta Ordinaria: ")
print(2 - 5) # -3
# Declaracion de variables
v1 = 10.4
v2 = 15
resultado = v2 - v1
print(resultado) # 4.6
#Phyton es el lenguaje predilecto para absolutamente todos los procesos matematicos

# 3er Nivel de importancia
# Multiplicacion ordinaria
print("Multiplicacion Ordinaria: ")
M1, M2 = 2,3.14
print(M1 * M2) # 6.28
#Division Ordinaria
print("-----------------")
print("Division Ordinaria: ")
M1,M2,M3,M4,M5,M6 = 2,5,6,5,4,5
print(M1/M2)
print(M3/M4)
print(M5/M6)
# Divison de Piso
print("-----------------")
print("Division de Piso")
print(M1//M2)
print(M3//M4)
print(M5//M6)

print( 6 / 2 * 3)

# Potencias
print("Potencias")
print(2 ** 3) # 8
P1,P2 = 7,2
print(P1 ** P2) # 49

# Area de un circulo
pi = 3.14
r = 4
A = pi * (r ** 2)
A

"""### Operacion String"""

HM = "Hola Mundo"
print(HM)

a,b = "ta","co"
print(a + " " + b) # Concatenar = unir

# Animal, debe tener un nombre, le debe gustar una fruta, debe tener una profesion
Animal = "Tortuga"
Nombre = "Rafael"
Fruta = "Durazno"
Profesion = "Ingeniero"
print(f"Hola soy {Nombre} y  soy un {Animal}, me gusta el {Fruta} y soy {Profesion}")

"""## Operaciones Logicas"""

# Empezamos con los operadores logicos <,>, <=,>=, and, or (SIEMPRE RETORNA UN BOOLEANO)

b1 = 4 > 5
b2 = 7 > 3
b3 = 14>14
b4 = 14>=14
b4

# Quieres un sandwich con todo
pan = True
queso = True
mayonesa = True
jamon = False
print(pan and queso and mayonesa and jamon)

print(True * 20)
print(False * 10)